import { primaryKey, oneOf, manyOf } from '@mswjs/data';

let idCounter = 1;

export default {
  id: primaryKey(() => String(idCounter++)),
  firstName: String,
  lastName: String,
  middleName: String,
  displayName: String,
  phone: String,
  email: String,
  preferredEmail: String,
  addedViaIlios: Boolean,
  enabled: Boolean,
  campusId: String,
  otherId: String,
  examined: Boolean,
  userSyncIgnore: Boolean,
  icsFeedKey: String,
  root: Boolean,
  reports: manyOf('report'),
  school: oneOf('school'),
  authentication: oneOf('authentication'),
  directedCourses: manyOf('course'),
  administeredCourses: manyOf('course'),
  studentAdvisedCourses: manyOf('course'),
  studentAdvisedSessions: manyOf('session'),
  learnerGroups: manyOf('learnerGroup'),
  instructedLearnerGroups: manyOf('learnerGroup'),
  instructorGroups: manyOf('instructorGroup'),
  instructorIlmSessions: manyOf('ilmSession'),
  learnerIlmSessions: manyOf('ilmSession'),
  offerings: manyOf('offering'),
  instructedOfferings: manyOf('offering'),
  programYears: manyOf('programYear'),
  roles: manyOf('userRole'),
  directedSchools: manyOf('school'),
  administeredSchools: manyOf('school'),
  administeredSessions: manyOf('session'),
  directedPrograms: manyOf('program'),
  cohorts: manyOf('cohort'),
  primaryCohort: oneOf('cohort'),
  pendingUserUpdates: manyOf('pendingUserUpdate'),
  administeredCurriculumInventoryReports: manyOf('curriculumInventoryReport'),
  sessionMaterialStatuses: manyOf('userSessionMaterialStatus'),
};
