# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  IMAGE: 'Ubuntu-16.04'
  CC_TEST_REPORTER_ID: 8c510ad3aa4b1a2a3d504dfdbcc5605e7966c019dc1e9b68a815de50b946ebc6
  COVERAGE: true
  MOZ_HEADLESS: 1
  SENTRY_ORG: ilios
  SENTRY_PROJECT: frontend
  NODE_VERSION: '10.x'
  GIT_BRANCH: $[ coalesce(variables['System.PullRequest.SourceBranch'], variables['Build.SourceBranchName'], 'not-found') ]
  GIT_COMMIT_SHA: $[ coalesce(variables['System.PullRequest.SourceCommitId'], variables['Build.SourceVersion'], 'not-found') ]

jobs:
- job: tests
  pool:
    vmImage: $(IMAGE)
  variables:
    SW_DISABLED: true
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
  - script: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - script: chmod +x ./cc-test-reporter
  - script: ./cc-test-reporter before-build
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      command: install
  - task: Npm@1
    displayName: 'lint style'
    inputs:
      command: custom
      customCommand: 'run lint:style'
  - task: Npm@1
    displayName: 'lint templates'
    inputs:
      command: custom
      customCommand: 'run lint:hbs'
  - task: Npm@1
    displayName: 'lint scripts'
    inputs:
      command: custom
      customCommand: 'run lint:js'
  - task: Npm@1
    displayName: 'npm test'
    inputs:
      command: custom
      customCommand: 'test'
  - script: ./cc-test-reporter format-coverage --input-type=cobertura coverage/cobertura-coverage.xml
  - script: ./cc-test-reporter upload-coverage
