# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/javascript

variables:
  IMAGE: 'Ubuntu-16.04'
  CC_TEST_REPORTER_ID: 8c510ad3aa4b1a2a3d504dfdbcc5605e7966c019dc1e9b68a815de50b946ebc6
  COVERAGE: true
  MOZ_HEADLESS: 1
  SENTRY_ORG: ilios
  SENTRY_PROJECT: frontend
  NODE_VERSION: '10.x'

jobs:
- job: tests
  pool:
    vmImage: $(IMAGE)
  variables:
    SW_DISABLED: true
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(NODE_VERSION)
  - script: npm config set spin false
  - script: npm install
  - script: npm run lint:style
  - script: npm run lint:hbs
  - script: npm run lint:js
  - script: npm test
