packages:
  - "packages/frontend"
  - "packages/ilios-common"
  - "packages/lti-course-manager"
  - "packages/lti-dashboard"
  - "packages/test-app"

# Protect against package ecosystem threats
minimumReleaseAge: 1440 # only install things that are at least one day old
trustPolicy: no-downgrade # never install anything where the publication provenance is less than it was
blockExoticSubdeps: true # block installing things not from the registry
