// see https://github.com/ember-intl/ember-intl/blob/main/packages/ember-intl-lint/docs/configuration.md#
export default {
  addonPaths: ['../ilios-common'],
  lintRules: {
    'no-unused-keys': {
      ignores: [
        'errors.duplicateUsername',
        'errors.invalidChangeAlertRecipients',
        'errors.reportMissingAcademicYear',
        'errors.reportMissingCompetency',
        'errors.reportMissingCourse',
        'errors.reportMissingInstructor',
        'errors.reportMissingInstructorGroup',
        'errors.reportMissingLearningMaterial',
        'errors.reportMissingMeshTerm',
        'errors.reportMissingObjectForCompetency',
        'errors.reportMissingObjectForInstructor',
        'errors.reportMissingObjectForInstructorGroup',
        'errors.reportMissingObjectForMeshTerm',
        'errors.reportMissingObjectForProgram',
        'errors.reportMissingObjectForSessionType',
        'errors.reportMissingObjectForTerm',
        'errors.reportMissingProgram',
        'errors.reportMissingProgramYear',
        'errors.reportMissingSession',
        'errors.reportMissingSessionType',
        'errors.reportMissingTerm',
        'general.badCredentials',
        'general.id',
        'general.language.en-us',
        'general.language.es',
        'general.language.fr',
        'general.pendingUserUpdates.missingFromDirectory',
      ],
    },
  },
};
