module.exports = function () {
  return {
    'pro-light-svg-icons': ['clipboard-list', 'lightbulb-slash'],
    'free-brands-svg-icons': ['black-tie'],
    'free-solid-svg-icons': [
      'angle-down',
      'angle-left',
      'angle-right',
      'arrow-circle-up',
      'asterisk',
      'bars',
      'bold',
      'book',
      'calendar',
      'chevron-right',
      'face-meh',
      'file-lines',
      'gears',
      'globe',
      'graduation-cap',
      'house',
      'italic',
      'list-ol',
      'list-ul',
      'paragraph',
      'rectangle-list',
      'rotate',
      'subscript',
      'sun',
      'superscript',
      'table',
      'truck-medical',
      'turn-down',
      'turn-up',
      'unlock',
      'user-doctor',
    ],
  };
};
