module.exports = function () {
  return {
    'pro-light-svg-icons': ['clipboard-list', 'lightbulb-slash'],
    'pro-solid-svg-icons': ['lightbulb-on'],
    'free-brands-svg-icons': ['black-tie'],
    'free-solid-svg-icons': [
      'angle-down',
      'angle-left',
      'angle-right',
      'arrow-circle-up',
      'ban',
      'bars',
      'bold',
      'book',
      'calendar',
      'caret-right',
      'caret-down',
      'check',
      'circle-exclamation',
      'clock',
      'cloud',
      'download',
      'ellipsis',
      'file-audio',
      'file-pdf',
      'file-powerpoint',
      'file-video',
      'file',
      'gears',
      'globe',
      'graduation-cap',
      'home',
      'info-circle',
      'italic',
      'level-down-alt',
      'level-up-alt',
      'link',
      'list-alt',
      'list-ol',
      'list-ul',
      'lock',
      'meh',
      'paragraph',
      'search',
      'sort-alpha-down',
      'sort-alpha-up',
      'sort-numeric-down',
      'sort-numeric-up',
      'sort',
      'spinner',
      'square-up-right',
      'star-half-alt',
      'star',
      'subscript',
      'sun',
      'superscript',
      'sync',
      'table',
      'triangle-exclamation',
      'truck-medical',
      'university',
      'unlock',
      'user-md',
    ],
  };
};
