import { A } from '@ember/array';

const models = [
  'model:aamc-method',
  'model:aamc-pcrs',
  'model:aamc-resource-type',
  'model:academic-year',
  'model:assessment-option',
  'model:authentication',
  'model:cohort',
  'model:competency',
  'model:course-learning-material',
  'model:course',
  'model:course-clerkship-type',
  'model:curriculum-inventory-academic-level',
  'model:curriculum-inventory-export',
  'model:curriculum-inventory-institution',
  'model:curriculum-inventory-report',
  'model:curriculum-inventory-sequence-block',
  'model:curriculum-inventory-sequence-block-session',
  'model:curriculum-inventory-sequence',
  'model:department',
  'model:ilm-session',
  'model:instructor-group',
  'model:learner-group',
  'model:learning-material-status',
  'model:learning-material-user-role',
  'model:learning-material',
  'model:mesh-concept',
  'model:mesh-descriptor',
  'model:mesh-previous-indexing',
  'model:mesh-qualifier',
  'model:mesh-term',
  'model:mesh-tree',
  'model:objective',
  'model:offering',
  'model:pending-user-update',
  'model:permission',
  'model:program-year',
  'model:program',
  'model:program-year-steward',
  'model:report',
  'model:school',
  'model:school-config',
  'model:session-description',
  'model:session-learning-material',
  'model:session-type',
  'model:session',
  'model:term',
  'model:user-made-reminder',
  'model:user-role',
  'model:user',
  'model:vocabulary',
];

export default A(models);
