// see https://github.com/ember-intl/ember-intl/blob/main/packages/ember-intl-lint/docs/configuration.md#
export default {
  lintRules: {
    'no-unused-keys': {
      ignores: [
        'errors.accepted',
        'errors.after',
        'errors.agreementRequired',
        'errors.before',
        'errors.blank',
        'errors.collection',
        'errors.confirmation',
        'errors.date',
        'errors.email',
        'errors.empty',
        'errors.equalTo',
        'errors.even',
        'errors.exclusion',
        'errors.greaterThan',
        'errors.greaterThanOrEqualTo',
        'errors.inclusion',
        'errors.invalid',
        'errors.lessThan',
        'errors.lessThanOrEqualTo',
        'errors.minimum',
        'errors.missingFile',
        'errors.notANumber',
        'errors.notAnInteger',
        'errors.odd',
        'errors.onOrAfter',
        'errors.onOrBefore',
        'errors.otherThan',
        'errors.phone',
        'errors.positive',
        'errors.present',
        'errors.required',
        'errors.singular',
        'errors.tooLong',
        'errors.tooShort',
        'errors.url',
        'errors.wrongDateFormat',
        'errors.wrongLength',
      ],
    },
  },
};
