name: Nightly

on:
  schedule:
    - cron: "15 9 * * 0-5" # nightly, S-F
  workflow_dispatch: null

env:
  SW_DISABLED: true
  COVERAGE: false

jobs:
  percy:
    name: Update Base Build On Percy
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workspace:
          - frontend
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm
      - run: pnpm install
      - name: Run Percy Tests
        run: pnpm --filter ${{ matrix.workspace }} exec percy exec -- ember test --filter="Acceptance"
        env:
          PERCY_TOKEN: "web_1899a9764a4891f3a19b87e52aa1ae038359e28ba550daa6bad00d0e0a230a33"
