name: Update pnpm Version
on:
  schedule:
    - cron: "0 23 * * 2" # Weekly on Tuesday afternoons (UTC)
  workflow_dispatch:

jobs:
  update-pnpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: Get latest pnpm version
        run: |
          PNPM_VERSION="$(npm view pnpm version)" # get the latest version of pnpm from the registry
          echo ${PNPM_VERSION}
          echo "pnpm_version=${PNPM_VERSION}" >> $GITHUB_ENV
      - name: Update package.json
        run: |
          jq '.packageManager = "pnpm@'"${{ env.pnpm_version }}"'"' package.json > temp.json
          mv temp.json package.json
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.ZORGBORT_TOKEN }}
          commit-message: Update PNPM to v${{ env.pnpm_version }}
          title: Update PNPM to v${{ env.pnpm_version }}
          body: |
            Update PNPM to v${{ env.pnpm_version }} the latest release.
            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-pnpm-version
          labels: dependencies
      - name: Approve Pull Request
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr review --approve -b "Auto Approved" ${{ steps.cpr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable Pull Request Automerge and Label for Tests
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: |
          gh pr edit --add-label "run ui tests" ${{ steps.cpr.outputs.pull-request-number }}
          gh pr merge --merge --auto ${{ steps.cpr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.ZORGBORT_TOKEN }}
      - uses: act10ns/slack@v2
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ILIOS_DEPLOYMENT_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          message: Update PNPM Job Failed {{ env.GITHUB_SERVER_URL }}/{{ env.GITHUB_REPOSITORY }}/actions/runs/{{ env.GITHUB_RUN_ID }}
